name: Production Release

on:
  workflow_dispatch: {}

jobs:
  Development:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - name: Run on env
      run: echo "I am running on ${{ github.job }}"

  Stage:
    runs-on: ubuntu-latest
    environment: STAGE
    needs: Development
    steps:
    - name: Run on env
      run: echo "I am running on ${{ github.job }}"

  Production:
    runs-on: ubuntu-latest
    environment: PROD
    needs: Stage
    steps:
    - name: Run on env
      run: echo "I am running on ${{ github.job }}"
